### ISSUE TITLE
[FR] Please add C++ support, out of the box.

### ISSUE THREAD

**Issue by kacperpaczos** [flathub/org.jupyter.JupyterLab#13]
I believe that the Flatpak version of the application has the ability and should use it to provide all possible solutions, without additional configuration.

Please add support for C++.

**Comment by kpthedev** [comment]
I'm not very familiar with tools for C++ in Jupyter. However, I tested a conda environment with the `xeus-cling` package you used in your PR and it seems to be working.

The JupyterLab Desktop application automatically finds conda environments that are in your home directory and have JupyterLab installed—this would be the ideal way to use these C++ tools.
