### ISSUE TITLE
Python environment not found.

### ISSUE THREAD

**Issue by almereyda** [flathub/org.jupyter.JupyterLab#2]
When launching JupyterLab Desktop from the Flatpak distribution, no Python environment is available.

![image](https://user-images.githubusercontent.com/1645308/233867458-e122d904-8fa9-4914-bec5-e01bb00710e1.png)

This is also the case after successfully using the bundled installer and restarting the application.

![image](https://user-images.githubusercontent.com/1645308/233867522-d2dfa9b9-08d0-4865-937e-3318eb72801d.png)

It also doesn't work when switching to the host system's Python, which is expected in Flatpak.

![image](https://user-images.githubusercontent.com/1645308/233867688-d1cdd5cb-f715-40ee-bc84-3332bcf34b1c.png)

also not with `filesystem=host-os` permission in Flatseal.

**Comment by kpthedev** [comment]
The bundled environment should be created in `~/.var/app/org.jupyter.JupyterLab/config/jupyterlab-desktop/jlab_server`. Could you check if that directory was created? The `filesystem=host-os` permission isn't needed for the bundled environment. 

The custom environments refers to either conda environments or venvs. You will need the `filesystem=home` permission to discover custom environments. The documentation explains how to set that up [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#how-to-create-a-custom-python-environment).

**Comment by almereyda** [comment]
I will check this weekend, thanks for the pointer!

**Comment by glemi** [comment]
I have the exact same problem on Windows.

**Comment by almereyda** [comment]
I didn't know the Flatpak runs on Windows.

Maybe your comment is better aimed against https://github.com/jupyterlab/jupyterlab-desktop?

This here is the Flatpak repository, targeting the Flatpak distribution of JupyterLab Desktop.

**Comment by bbenson-redhat** [comment]
Has the fix propagated out to v4.0.7?  I am still experiencing this problem when getting the app from Flathub.

**Comment by kpthedev** [comment]
@bbenson-redhat When you first open the app, there should be a banner at the bottom that has an option to "Install using the bundled installer." That should set up the included Python environment. If the banner doesn't appear, you can go into the settings and in the "Server" tab it should have an option to install the bundled environment.

**Comment by bbenson-redhat** [comment]
Yes, thanks.  I'm sorry the "Install using the bundled installer." was set in a grey typeface which led me away from believing it was clickable.  Maybe that color could be changed.  Thanks so much!

**Comment by kiliansinger** [comment]
I had the same issue
