### ISSUE TITLE
Package so that nvidia cuda capabilities are passed through?

### ISSUE THREAD

**Issue by pacificera** [flathub/org.jupyter.JupyterLab#4]
Thanks for this flatpak.  It is very promising.

Is it possible to package Jupyter in a flatpak so that the nvidia cuda capabilities are passed into the container?

I have nvidia enabled in my host system and can create nvidia capable containers, painstakingly, with commands like this:

podman run \
    --user 1000:1000 \
    --security-opt=no-new-privileges \
    --cap-drop=ALL \
    --security-opt label=type:nvidia_container_t  \
	-d -it -p 8848:8888 \
	-v $(pwd)/data:/home/jovyan/work \
	-e JUPYTER_ENABLE_LAB=yes \
	 cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04_python-only
	 
It would be awesome if your flatpak had this capability.

**Comment by kpthedev** [comment]
The bundled environment comes with a couple of scientific libraries installed, but none that require CUDA. You could try creating a custom environment (details [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#how-to-create-a-custom-python-environment)) and installing your CUDA packages inside that environment.
